### PR TITLE
Added variables on makefile to make it easier to change and more

### PR DESCRIPTION
**Pull request by lima-limon-inc**
readable

### CODE REVIEW

**Comment by lima-limon-inc** [comment]
It's a minor change, but I think it makes it easier to change in the future

**Comment by pog102** [comment]
This is great! This is my first legitimate project, so I'm quite inexperienced at this. However, I'm hoping to improve. :D

**Comment by lima-limon-inc** [comment]
I'd say it was a pretty successful first project!!! You've had tons of support.
It's a really cool idea!!

**Comment by lima-limon-inc** [comment]
Btw,  you could consider make a Github "release". It makes packaging easier (as it bundles all the source code into a tar bar automatically) . It also has the added "benefit" of having versions like "1.0", "2.0", "2.4".
Just a suggestion however

**Pull request merged**
